import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{Moon,Sun,Check,Plus,Trash2,LogOut,Heart,Link2,Copy,Target,CalendarDays,UserRound,Home,Camera,Flame,CalendarCheck,Bell,CheckCheck}from'lucide-react';import{supabase}from'./lib/supabase';import*as api from'./lib/api';import{fmtDate,pct,streak,today,dateKey,addDaysKey,monthStartKey,nextMonthStartKey,monthEndKey}from'./lib/utils';import type{Goal,Profile,Task,Connection,Habit,Notification,ReactionType}from'./lib/types';import'./styles.css';

type SessionUser={id:string;email?:string};
type View='home'|'goals'|'history'|'partner'|'profile';
function App(){const [user,setUser]=useState<SessionUser|null>(null);const [loading,setLoading]=useState(true);const [profile,setProfile]=useState<Profile|null>(null);const [connection,setConnection]=useState<Connection|null>(null);const [partner,setPartner]=useState<Profile|null>(null);const [view,setViewState]=useState<View>('home'); const setView=(next:View)=>{setViewState(next)};const [dark,setDark]=useState(localStorage.getItem('theme')==='dark');
useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light')},[dark]);
useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user?{id:data.session.user.id,email:data.session.user.email}:null)).finally(()=>setLoading(false));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user?{id:s.user.id,email:s.user.email}:null));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!user)return;Promise.all([api.getProfile(user.id),api.getConnection(user.id)]).then(async([p,c])=>{setProfile(p);setConnection(c);setPartner(null);if(c?.status==='connected'){const pid=c.requester_id===user.id?c.recipient_id:c.requester_id;if(pid)setPartner(await api.getProfile(pid))}}).catch(console.error)},[user]);
const [notifications,setNotifications]=useState<Notification[]>([]); const [notificationsOpen,setNotificationsOpen]=useState(false);
useEffect(()=>{if(!user)return;let active=true;api.getNotifications(user.id).then(x=>{if(active)setNotifications(x)}).catch(console.error);const channel=supabase.channel('rahletna-notifications-'+user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:'user_id=eq.'+user.id},payload=>setNotifications(prev=>[payload.new as Notification,...prev].slice(0,50))).subscribe();return()=>{active=false;supabase.removeChannel(channel)}},[user]);
async function readNotification(id:string){try{const n=await api.markNotificationRead(id,user.id);setNotifications(prev=>prev.map(x=>x.id===id?n:x))}catch(e){console.error(e)}}
async function readAllNotifications(){try{await api.markAllNotificationsRead(user.id);setNotifications(prev=>prev.map(x=>x.read_at?x:{...x,read_at:new Date().toISOString()}))}catch(e){console.error(e)}}
if(loading)return <div className="center"><div className="spinner"/></div>;if(!user)return <Auth/>;if(!profile||!profile.gender)return <ProfileSetup user={user} onDone={setProfile}/>;
return <Shell profile={profile} partner={partner} view={view} setView={setView} dark={dark} setDark={setDark} onLogout={()=>supabase.auth.signOut()} notifications={notifications} notificationsOpen={notificationsOpen} setNotificationsOpen={setNotificationsOpen} onReadNotification={readNotification} onReadAllNotifications={readAllNotifications}><Dashboard user={user} profile={profile} partner={partner} connection={connection} view={view} setView={setView} setConnection={setConnection} setPartner={setPartner} onProfileUpdated={setProfile}/></Shell>}

function Auth(){const[signup,setSignup]=useState(false);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[gender,setGender]=useState<'male'|'female'>('male');const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const r=signup?await supabase.auth.signUp({email,password,options:{data:{display_name:name,gender}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)setError(r.error.message);else if(signup&&!r.data.session)setError('تم إنشاء الحساب. راجع بريدك لتأكيد الحساب ثم سجّل الدخول.')}return <div className="auth"><div className="auth-card"><div className="logo">ر</div><h1>رحلتنا</h1><p>أنا أعمل على نفسي، وأنت تعمل على نفسك، لكننا لسنا وحدنا في الرحلة.</p><form onSubmit={submit}>{signup&&<><input required placeholder="اسمك" value={name} onChange={e=>setName(e.target.value)}/><label className="gender-label">أنا <select value={gender} onChange={e=>setGender(e.target.value as 'male'|'female')}><option value="male">ذكر</option><option value="female">أنثى</option></select></label></>}<input required type="email" placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength={6} type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'جاري التنفيذ…':signup?'إنشاء حساب':'تسجيل الدخول'}</button></form><button className="link" onClick={()=>setSignup(!signup)}>{signup?'لديك حساب؟ سجّل الدخول':'ليس لديك حساب؟ أنشئ حسابًا'}</button></div></div>}
function ProfileSetup({user,onDone}:{user:SessionUser;onDone:(p:Profile)=>void}){const[name,setName]=useState('');const[bio,setBio]=useState('');const[gender,setGender]=useState<'male'|'female'>('male');const[busy,setBusy]=useState(false);async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const p=await api.updateProfile(user.id,{display_name:name.trim(),bio:bio.trim(),gender});onDone(p)}catch(e){alert((e as Error).message)}finally{setBusy(false)}}return <div className="auth"><div className="auth-card"><div className="logo">ر</div><h1>خلينا نعرّفك</h1><p>بيانات بسيطة عشان رحلتك تكون شخصية أكتر.</p><form onSubmit={save}><input required placeholder="اسمك" value={name} onChange={e=>setName(e.target.value)}/><label className="gender-label">الجنس<select value={gender} onChange={e=>setGender(e.target.value as 'male'|'female')}><option value="male">ذكر</option><option value="female">أنثى</option></select></label><textarea placeholder="نبذة قصيرة عنك (اختياري)" value={bio} onChange={e=>setBio(e.target.value)}/><button className="primary" disabled={busy}>{busy?'حفظ…':'متابعة'}</button></form></div></div>}
function Connect({user,connection,onConnected,onBack}:{user:SessionUser;connection:Connection|null;onConnected:()=>void;onBack:()=>void}){const[code,setCode]=useState('');const[invite,setInvite]=useState(connection?.invite_code||'');const[busy,setBusy]=useState(false);async function create(){setBusy(true);try{const c=await api.createInvite(user.id);setInvite(c.invite_code)}catch(e){alert((e as Error).message)}finally{setBusy(false)}}async function join(){setBusy(true);try{await api.acceptInvite(code);onConnected()}catch(e){alert((e as Error).message)}finally{setBusy(false)}}return <div className="card connect-card">
<div className="connect-head"><div className="connect-icon"><Link2 size={24}/></div><div><h2>اربط شريكًا 🤝</h2><p>اختياري تمامًا. كمل رحلتك لوحدك أو شاركها مع شخص تثق به.</p></div></div>
{invite?<div className="invite"><div className="invite-code"><span>{invite}</span><button type="button" className="icon-btn" title="نسخ الكود" onClick={async()=>{try{await navigator.clipboard.writeText(invite);alert('تم نسخ كود الدعوة')}catch{alert('انسخ الكود يدويًا')}}}><Copy size={18}/></button></div><small>ابعت الكود للشخص الآخر عشان يربط حسابه بيك.</small></div>:<button type="button" className="primary connect-create" onClick={create} disabled={busy}><Link2 size={18}/> {busy?'جاري إنشاء الكود…':'إنشاء كود دعوة'}</button>}
<div className="connect-divider"><span>أو</span></div>
<div className="join-box"><label>عندك كود دعوة؟</label><div className="join-row"><input aria-label="كود الدعوة" placeholder="الصق كود الدعوة هنا" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button type="button" className="secondary join-btn" onClick={join} disabled={!code.trim()||busy}>{busy?'جاري…':'الانضمام'}</button></div></div>
{connection?.status==='pending'&&<div className="pending-box">⏳ مستني الطرف الآخر يستخدم كود الدعوة.</div>}
<button type="button" id="back-home-button" className="connect-back" onClick={(e)=>{e.preventDefault();e.stopPropagation();onBack()}}>← الرجوع للرئيسية</button>
</div>}
function Shell({children,profile,partner,view,setView,dark,setDark,onLogout,notifications,notificationsOpen,setNotificationsOpen,onReadNotification,onReadAllNotifications}:{children:React.ReactNode;profile:Profile;partner:Profile|null;view:string;setView:(v:string)=>void;dark:boolean;setDark:(v:boolean)=>void;onLogout:()=>void;notifications:Notification[];notificationsOpen:boolean;setNotificationsOpen:(v:boolean)=>void;onReadNotification:(id:string)=>void;onReadAllNotifications:()=>void}){const items=[['home','الرئيسية',Home],['goals','أهدافي',Target],['history','السجل',CalendarDays],['partner','الشريك',Heart],['profile','ملفي',UserRound]] as const;const unread=notifications.filter(n=>!n.read_at).length;return <div className="app"><aside><div className="brand"><div className="logo small">ر</div><span>رحلتنا</span></div><nav>{items.map(([id,label,Icon])=><button type="button" className={view===id?'active':''} onClick={()=>setView(id)} key={id}><Icon size={19}/>{label}</button>)}</nav><div className="side-bottom"><button type="button" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>} {dark?'الوضع النهاري':'الوضع الليلي'}</button><button type="button" onClick={onLogout}><LogOut size={18}/> خروج</button></div></aside><main><header><div><strong>مرحبًا، {profile.display_name} 👋</strong><span>{fmtDate(today())}</span></div><div className="header-actions">{partner?<div className="partner-mini"><Avatar profile={partner}/><span>{partner.display_name}</span></div>:<button type="button" className="secondary header-connect" onClick={()=>setView('partner')}><Link2 size={16}/> اربط شريك</button>}<button type="button" className="notification-trigger" aria-label="الإشعارات" onClick={()=>setNotificationsOpen(!notificationsOpen)}><Bell size={19}/>{unread>0&&<b>{unread>9?'9+':unread}</b>}</button></div></header>{notificationsOpen&&<NotificationPanel notifications={notifications} onRead={onReadNotification} onReadAll={onReadAllNotifications} onClose={()=>setNotificationsOpen(false)} onOpenPartner={()=>{setNotificationsOpen(false);setView('partner')}}/>}{children}</main></div>}
function NotificationPanel({notifications,onRead,onReadAll,onClose,onOpenPartner}:{notifications:Notification[];onRead:(id:string)=>void;onReadAll:()=>void;onClose:()=>void;onOpenPartner:()=>void}){return <div className="notifications-panel"><div className="notifications-head"><div><strong>الإشعارات</strong><span>{notifications.filter(n=>!n.read_at).length} غير مقروء</span></div><div><button type="button" className="icon-btn" title="تحديد الكل كمقروء" onClick={onReadAll}><CheckCheck size={17}/></button><button type="button" className="icon-btn" title="إغلاق" onClick={onClose}>×</button></div></div>{notifications.length?<div className="notifications-list">{notifications.map(n=><button type="button" className={`notification-item ${n.read_at?'read':''}`} key={n.id} onClick={()=>{if(!n.read_at)onRead(n.id);onOpenPartner()}}><span className="notification-icon">{n.type==='reaction'?'✨':'❤️'}</span><span><strong>{n.title}</strong><small>{n.body}</small><em>{new Date(n.created_at).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'})}</em></span>{!n.read_at&&<i/>}</button>)}</div>:<Empty text="مفيش إشعارات لسه."/>}</div>}

function Dashboard({user,profile,partner,connection,view,setConnection,setPartner,onProfileUpdated}:{user:SessionUser;profile:Profile;partner:Profile|null;connection:Connection|null;view:string;setConnection:(c:Connection|null)=>void;setPartner:(p:Profile|null)=>void;onProfileUpdated:(p:Profile)=>void;setView:(v:string)=>void}){
const[start,setStart]=useState(today());
const[own,setOwn]=useState<Task[]>([]);const[pTasks,setPTasks]=useState<Task[]>([]);const[goals,setGoals]=useState<Goal[]>([]);const[pGoals,setPGoals]=useState<Goal[]>([]);const[habits,setHabits]=useState<Habit[]>([]);const[pHabits,setPHabits]=useState<Habit[]>([]);const[habitLogs,setHabitLogs]=useState<import('./lib/types').HabitLog[]>([]);const[encouragements,setEncouragements]=useState<import('./lib/types').Encouragement[]>([]);
const[busy,setBusy]=useState(false);const[modal,setModal]=useState(false);const[toast,setToast]=useState('');const[message,setMessage]=useState('');const[reactions,setReactions]=useState<import('./lib/types').EncouragementReaction[]>([]);
const refresh=async()=>{const f=monthStartKey(today()),t=nextMonthStartKey(today());const partnerTasksPromise=partner?api.getTasks(partner.id,f,t):Promise.resolve([] as Task[]);const partnerGoalsPromise=partner?api.getGoals(partner.id):Promise.resolve([] as Goal[]);const partnerHabitsPromise=partner?api.getHabits(partner.id):Promise.resolve([] as Habit[]);const encouragementsPromise=partner?api.getEncouragements(user.id):Promise.resolve([] as import('./lib/types').Encouragement[]);const[a,b,g,pg,h,ph,l,e]=await Promise.all([api.getTasks(user.id,f,t),partnerTasksPromise,api.getGoals(user.id),partnerGoalsPromise,api.getHabits(user.id),partnerHabitsPromise,api.getHabitLogs(user.id,f,t),encouragementsPromise]);setOwn(a);setPTasks(b);setGoals(g);setPGoals(pg);setHabits(h);setPHabits(ph);setHabitLogs(l);setEncouragements(e);setReactions(await api.getReactions(e.map(x=>x.id)))};
useEffect(()=>{refresh().catch(e=>setToast((e as Error).message))},[user.id,partner?.id]);
useEffect(()=>{const channel=supabase.channel(`rahletna-live-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'tasks'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'habits'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'habit_logs'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'goals'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'milestones'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'encouragements'},()=>refresh().catch(()=>{})).on('postgres_changes',{event:'*',schema:'public',table:'encouragement_reactions'},()=>refresh().catch(()=>{})).subscribe();return()=>{supabase.removeChannel(channel)}},[user.id,partner?.id]);
const dayOwn=useMemo(()=>own.filter(t=>t.task_date===start),[own,start]);const dayP=useMemo(()=>pTasks.filter(t=>t.task_date===start),[pTasks,start]);const done=dayOwn.filter(t=>t.status==='completed').length;const pDone=dayP.filter(t=>t.status==='completed').length;const dayHabitLogs=habitLogs.filter(l=>l.log_date===start&&l.completed);const activeHabits=habits.filter(h=>h.active);
async function toggle(t:Task){setBusy(true);try{const next=t.status==='completed'?'pending':'completed';const u=await api.upsertTask({id:t.id,user_id:user.id,status:next,completed_at:next==='completed'?new Date().toISOString():null,updated_at:new Date().toISOString()});setOwn(x=>x.map(i=>i.id===u.id?u:i))}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
async function add(title:string,description:string,time:string,category:string,priority:string,goalId:string){try{const t=await api.upsertTask({user_id:user.id,title,description:description||null,due_time:time||null,task_date:start,status:'pending',category,priority:Number(priority) as 0|1|2|3,goal_id:goalId||null});setOwn(x=>[...x,t]);setModal(false)}catch(e){setToast((e as Error).message)}}
async function toggleHabit(h:Habit){setBusy(true);try{const existing=habitLogs.find(l=>l.habit_id===h.id&&l.log_date===start);const completed=!existing?.completed;const l=await api.logHabit(h.id,user.id,start,completed);setHabitLogs(x=>{const rest=x.filter(i=>i.id!==l.id);return[...rest,l]})}catch(e){setToast((e as Error).message)}finally{setBusy(false)}}
async function send(){if(!message.trim()||!partner)return;try{await api.sendEncouragement(user.id,partner.id,message.trim());setMessage('');setToast('وصلت الرسالة ❤️');const e=await api.getEncouragements(user.id);setEncouragements(e);setReactions(await api.getReactions(e.map(x=>x.id)))}catch(e){setToast((e as Error).message)}}
async function removeMessage(id:string){if(!window.confirm('حذف الرسالة؟'))return;try{await api.deleteEncouragement(id,user.id);setEncouragements(x=>x.filter(m=>m.id!==id))}catch(e){setToast((e as Error).message)}}
async function reactToMessage(id:string,reaction:ReactionType){try{await api.toggleReaction(id,user.id,reaction);setReactions(await api.getReactions(encouragements.map(x=>x.id)))}catch(e){setToast((e as Error).message)}}
function reactionCount(id:string,r:ReactionType){return reactions.filter(x=>x.encouragement_id===id&&x.reaction===r).length}
function hasReaction(id:string,r:ReactionType){return reactions.some(x=>x.encouragement_id===id&&x.reaction===r&&x.user_id===user.id)}
if(view==='goals')return <Goals user={user} goals={goals} habits={habits} refresh={refresh}/>;
if(view==='history')return <History user={user} tasks={own} habits={habits}/>;
if(view==='partner')return partner?<Partner partner={partner} tasks={pTasks} goals={pGoals} habits={pHabits} onBack={()=>setView('home')}/>:<Page title="الشريك" sub="رحلتك ملكك، والشريك اختيار تقدر تضيفه في أي وقت."><Connect user={user} connection={connection} onConnected={async()=>{const c=await api.getConnection(user.id);setConnection(c);if(c?.status==='connected'){const pid=c.requester_id===user.id?c.recipient_id:c.requester_id;if(pid)setPartner(await api.getProfile(pid))}}} onBack={()=>setView('home')}/></Page>;
if(view==='profile')return <ProfileView profile={profile} onSaved={onProfileUpdated}/>;
const visibleMessages=encouragements.slice(0,8);
return <>
<section className="hero"><div><span className="eyebrow">اليوم • {fmtDate(start)}</span><h1>خطوة صغيرة كل يوم<br/><em>تقرّبك من نفسك اللي نفسك فيها.</em></h1><p>{profile.gender==='female'?'مش مطلوب منكِ الكمال. المطلوب إنكِ تكمّلي.':'مش مطلوب منك الكمال. المطلوب إنك تكمل.'}</p></div><div className="ring" style={{'--p':`${pct(done,dayOwn.length)}%`} as React.CSSProperties}><b>{pct(done,dayOwn.length)}%</b><span>إنجازي اليوم</span></div></section>
<DashboardModeBanner profile={profile} partner={partner} onPartner={()=>setView('partner')}/><SmartDashboard tasks={own} goals={goals} habits={habits} habitLogs={habitLogs} yesterdayTasks={own}/><div className="grid two"><section className="card"><div className="section-head"><div><h2>خطواتي اليوم</h2><span>{done} من {dayOwn.length} مكتملة</span></div><button className="icon-btn" onClick={()=>setModal(true)}><Plus size={20}/></button></div><div className="progress"><i style={{width:`${pct(done,dayOwn.length)}%`}}/></div>{dayOwn.length?<div className="tasks">{dayOwn.map(t=><TaskRow key={t.id} task={t} mine onToggle={()=>toggle(t)} onDelete={async()=>{try{await api.deleteTask(t.id);setOwn(x=>x.filter(i=>i.id!==t.id))}catch(e){setToast((e as Error).message)}}}/>)}</div>:<Empty text="لسه مفيش خطوات لليوم. ابدأ بأول خطوة."/>}</section>
{partner?<section className="card partner-card"><div className="section-head"><div><h2>رحلة {partner.display_name} ❤️</h2><span>{pDone} من {dayP.length} خطوات مكتملة اليوم</span></div><Avatar profile={partner}/></div><div className="partner-profile-mini"><span>🎯 {pGoals.filter(g=>g.status==='active').length} أهداف نشطة</span><span>🌱 {pHabits.filter(h=>h.active).length} عادات نشطة</span><span>🔥 {streak(pTasks)} يوم Streak</span><span>📊 {pct(pDone,dayP.length)}% اليوم</span></div><div className="progress"><i style={{width:`${pct(pDone,dayP.length)}%`}}/></div>{dayP.length?<div className="tasks">{dayP.map(t=><TaskRow key={t.id} task={t} mine={false}/>)}</div>:<Empty text="لسه مفيش خطوات مسجلة لليوم."/>}<button type="button" id="partner-open-button" className="secondary partner-open" onClick={(e)=>{e.preventDefault();e.stopPropagation();setView('partner')}}>عرض رحلته كاملة</button><div className="encourage"><Heart size={18}/><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="ابعت له كلمة تشجيع…"/><button onClick={send}>إرسال</button></div></section>:<section className="card partner-card solo-card"><div className="section-head"><div><h2>رحلتك الشخصية 👤</h2><span>الوضع الفردي — بياناتك ملكك</span></div><span className="badge">Solo</span></div><p>كل أهدافك وعاداتك ومهامك شغالة بشكل طبيعي من غير شريك. ولما تحب، تقدر تربط شخصًا في أي وقت من صفحة الشريك.</p><div className="solo-highlights"><span>🎯 {goals.filter(g=>g.status==='active').length} أهداف نشطة</span><span>🌱 {activeHabits.length} عادات</span><span>🔥 {streak(own)} يوم Streak</span></div><button type="button" id="solo-add-partner-button" className="secondary" onClick={(e)=>{e.preventDefault();e.stopPropagation();setView('partner')}}><Link2 size={16}/> إضافة شريك</button></section>}</div>
<section className="card"><div className="section-head"><div><h2>عاداتي اليوم 🌱</h2><span>{dayHabitLogs.length} من {activeHabits.length} مكتملة</span></div><CalendarCheck size={20}/></div>{activeHabits.length?<div className="tasks">{activeHabits.map(h=>{const doneToday=dayHabitLogs.some(l=>l.habit_id===h.id);return <div className="task" key={h.id}><button className={`check ${doneToday?'done':''}`} onClick={()=>toggleHabit(h)} disabled={busy}>{doneToday&&<Check size={15}/>}</button><div className="task-main"><strong className={doneToday?'strike':''}>{h.title}</strong><span>{h.frequency} • {h.target_per_week} مرات/أسبوع</span></div></div>})}</div>:<Empty text="أضف أول عادة من صفحة أهدافي."/>}</section>
<section className="card messages-card"><div className="section-head"><div><h2>كلمات بيننا 💜</h2><span>تشجيع بسيط يكمل الرحلة</span></div></div>{visibleMessages.length?<div className="messages-list">{visibleMessages.map(m=><div className={`message ${m.sender_id===user.id?'mine':''}`} key={m.id}><div className="message-avatar">{m.sender_id===user.id?profile.display_name[0]:partner.display_name[0]}</div><div className="message-content"><strong>{m.sender_id===user.id?'أنت':partner.display_name}</strong><p>{m.message}</p><small>{new Date(m.created_at).toLocaleString('ar-EG',{dateStyle:'short',timeStyle:'short'})}</small><div className="reaction-row">{([['heart','❤️'],['fire','🔥'],['clap','👏'],['muscle','💪'],['star','⭐']] as const).map(([r,emoji])=><button type="button" key={r} className={`reaction-btn ${hasReaction(m.id,r)?'selected':''}`} onClick={()=>reactToMessage(m.id,r)}><span>{emoji}</span>{reactionCount(m.id,r)>0&&<b>{reactionCount(m.id,r)}</b>}</button>)}</div></div>{m.sender_id===user.id&&<button type="button" className="trash" title="حذف الرسالة" onClick={()=>removeMessage(m.id)}><Trash2 size={15}/></button>}</div>)}</div>:<Empty text="لسه مفيش رسائل. ابعت أول كلمة تشجيع ❤️"/>}</section>
<section className="stats grid three"><Stat label="سلسلة إنجازي" value={`${streak(own)} يوم`} icon="🔥"/><Stat label="أهدافي النشطة" value={`${goals.filter(g=>g.status==='active').length}`} icon="🎯"/><Stat label="عاداتي النشطة" value={`${activeHabits.length}`} icon="🌱"/></section>
{modal&&<AddModal goals={goals} onClose={()=>setModal(false)} onAdd={add} busy={busy}/>} {toast&&<button className="toast" onClick={()=>setToast('')}>{toast}</button>}
</>}

function DashboardModeBanner({profile,partner,onPartner}:{profile:Profile;partner:Profile|null;onPartner:()=>void}){const feminine=profile.gender==='female';return <section className={`mode-banner ${partner?'connected':'solo'}`}><div className="mode-icon">{partner?'❤️':'👤'}</div><div className="mode-copy"><strong>{partner?`رحلتك مع ${partner.display_name}`:'رحلتك الشخصية'}</strong><span>{partner?(feminine?'أنتِ وشريكك تمشون في نفس الرحلة، وكل واحد مسؤول عن خطواته.':'أنت وشريكك تمشون في نفس الرحلة، وكل واحد مسؤول عن خطواته.'):(feminine?'أنتِ في الوضع الفردي. ابني عاداتك وأهدافك بطريقتك، ولما تحبي أضيفي شريكًا.':'أنت في الوضع الفردي. ابنِ عاداتك وأهدافك بطريقتك، ولما تحب أضف شريكًا.')}</span></div>{!partner&&<button type="button" id="add-partner-button" className="secondary" onClick={(e)=>{e.preventDefault();e.stopPropagation();onPartner()}}><Link2 size={16}/> إضافة شريك</button>}{partner&&<button type="button" id="partner-top-button" className="secondary" onClick={(e)=>{e.preventDefault();e.stopPropagation();onPartner()}}>عرض الرحلة ❤️</button>}</section>}

function SmartDashboard({tasks,goals,habits,habitLogs}:{tasks:Task[];goals:Goal[];habits:Habit[];habitLogs:import('./lib/types').HabitLog[];yesterdayTasks?:Task[]}){
 const now=new Date();
 const day=dateKey(now); const yesterday=addDaysKey(day,-1);
 const todayTasks=tasks.filter(t=>t.task_date===day); const yTasks=tasks.filter(t=>t.task_date===yesterday);
 const todayHabitDone=habitLogs.filter(l=>l.log_date===day&&l.completed).length;
 const yHabitDone=habitLogs.filter(l=>l.log_date===yesterday&&l.completed).length;
 const todayTotal=todayTasks.length+habits.filter(h=>h.active).length;
 const todayDone=todayTasks.filter(t=>t.status==='completed').length+todayHabitDone;
 const yTotal=yTasks.length+habits.filter(h=>h.active).length;
 const yDone=yTasks.filter(t=>t.status==='completed').length+yHabitDone;
 const todayPct=pct(todayDone,todayTotal), yesterdayPct=pct(yDone,yTotal);
 const delta=todayPct-yesterdayPct;
 const important=todayTasks.find(t=>t.status!=='completed'&&Number(t.priority)>=3)||todayTasks.find(t=>t.status!=='completed')||null;
 const activeGoals=goals.filter(g=>g.status==='active');
 const completedTasks=tasks.filter(t=>t.status==='completed').length;
 const completedHabits=habitLogs.filter(l=>l.completed).length;
 const achievements=[
  {icon:'🌱',title:'أول عادة',ok:habits.length>=1,desc:'أضفت أول عادة لرحلتك.'},
  {icon:'🎯',title:'أول هدف',ok:goals.length>=1,desc:'أنشأت أول هدف.'},
  {icon:'🏆',title:'أول هدف مكتمل',ok:goals.some(g=>g.status==='completed'),desc:'أكملت هدفًا كاملًا.'},
  {icon:'🔥',title:'7 أيام إنجاز',ok:streak(tasks)>=7,desc:'حافظت على سلسلة 7 أيام من المهام.'},
  {icon:'💯',title:'10 عادات مكتملة',ok:completedHabits>=10,desc:'سجلت 10 إنجازات للعادات.'},
  {icon:'✨',title:'100 مهمة',ok:completedTasks>=100,desc:'أكملت 100 مهمة.'},
 ];
 const weekStart=new Date(now); weekStart.setDate(now.getDate()-6); const weekStartKey=dateKey(weekStart);
 const weekTasks=tasks.filter(t=>t.task_date>=weekStartKey&&t.task_date<=day);
 const weekLogs=habitLogs.filter(l=>l.log_date>=weekStartKey&&l.log_date<=day&&l.completed);
 const weekTotal=weekTasks.length+habits.filter(h=>h.active).length*7;
 const weekDone=weekTasks.filter(t=>t.status==='completed').length+weekLogs.length;
 const weekPct=pct(weekDone,weekTotal);
 const missed=weekTasks.filter(t=>t.status!=='completed').length;
 const bestHabit=habits.map(h=>({h,n:weekLogs.filter(l=>l.habit_id===h.id).length})).sort((a,b)=>b.n-a.n)[0];
 return <>
  <div className="grid three smart-stats">
   <Stat label="إنجاز اليوم" value={`${todayPct}%`} icon="📊"/>
   <Stat label="مقارنة بأمس" value={`${delta>=0?'+':''}${delta}%`} icon={delta>=0?'📈':'📉'}/>
   <Stat label="الأهداف النشطة" value={`${activeGoals.length}`} icon="🎯"/>
  </div>
  <div className="grid two smart-grid">
   <section className="card"><div className="section-head"><div><h2>أهم شيء عليك اليوم ⭐</h2><span>ابدأ بالأقرب للتنفيذ</span></div></div>{important?<div className="priority-focus"><strong>{important.title}</strong><span>{important.category||'عام'} {important.due_time?`• ${important.due_time.slice(0,5)}`:''}</span></div>:<Empty text="خلصت كل خطوات اليوم. خُد نفس وكمّل براحة ❤️"/>}</section>
   <section className="card"><div className="section-head"><div><h2>ملخص الأسبوع 📈</h2><span>آخر 7 أيام</span></div><b>{weekPct}%</b></div><div className="progress"><i style={{width:`${weekPct}%`}}/></div><div className="review-grid"><div><strong>{weekDone}</strong><span>إنجاز</span></div><div><strong>{missed}</strong><span>لم يكتمل</span></div><div><strong>{bestHabit?.n||0}</strong><span>{bestHabit?.h.title||'أفضل عادة'}</span></div></div></section>
  </div>
  <div className="grid two smart-grid">
   <section className="card"><div className="section-head"><div><h2>أهدافي الحالية 🎯</h2><span>التقدم حسب المراحل</span></div></div>{activeGoals.length?activeGoals.slice(0,4).map(g=><div className="smart-goal" key={g.id}><div><strong>{g.title}</strong><span>{g.end_date||g.target_date?'حتى '+(g.end_date||g.target_date):'مستمر'}</span></div><span className="badge">نشط</span></div>):<Empty text="ابدأ بهدف واحد واضح، والباقي هييجي."/>}</section>
   <section className="card"><div className="section-head"><div><h2>إنجازاتي 🏆</h2><span>محطات في رحلتك</span></div></div><div className="achievements">{achievements.map(a=><div className={`achievement ${a.ok?'unlocked':''}`} key={a.title}><span>{a.icon}</span><div><strong>{a.title}</strong><small>{a.ok?a.desc:'لسه قدامك خطوة.'}</small></div></div>)}</div></section>
  </div>
 </>;
}

function TaskRow({task,mine,onToggle,onDelete}:{task:Task;mine:boolean;onToggle?:()=>void;onDelete?:()=>void}){return <div className="task"><button className={`check ${task.status==='completed'?'done':''}`} disabled={!mine} onClick={onToggle}>{task.status==='completed'&&<Check size={15}/>}</button><div className="task-main"><strong className={task.status==='completed'?'strike':''}>{task.title}</strong><span>{task.category}{task.due_time?` • ${task.due_time.slice(0,5)}`:''}</span></div>{mine&&<button className="trash" onClick={onDelete}><Trash2 size={16}/></button>}</div>}
function AddModal({onClose,onAdd,busy,goals}:{onClose:()=>void;onAdd:(a:string,b:string,c:string,d:string,e:string,f:string)=>void;busy:boolean;goals:Goal[]}){const[a,setA]=useState('');const[b,setB]=useState('');const[c,setC]=useState('');const[d,setD]=useState('عام');const[e,setE]=useState('2');const[f,setF]=useState('');return <div className="overlay"><form className="modal" onSubmit={x=>{x.preventDefault();if(a.trim())onAdd(a,b,c,d,e,f)}}><div className="section-head"><h2>خطوة جديدة</h2><button type="button" className="icon-btn" onClick={onClose}>×</button></div><input required autoFocus placeholder="إيه الخطوة؟" value={a} onChange={x=>setA(x.target.value)}/><textarea placeholder="تفاصيل اختيارية" value={b} onChange={x=>setB(x.target.value)}/><div className="form-grid"><input type="time" value={c} onChange={x=>setC(x.target.value)}/><input placeholder="التصنيف" value={d} onChange={x=>setD(x.target.value)}/><select value={e} onChange={x=>setE(x.target.value)}><option value="0">عادي</option><option value="1">منخفضة</option><option value="2">متوسطة</option><option value="3">عالية</option></select></div>{goals.length>0&&<select value={f} onChange={x=>setF(x.target.value)}><option value="">بدون هدف</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select>}<button className="primary" disabled={busy}>إضافة الخطوة</button></form></div>}
function Goals({user,goals,habits,refresh}:{user:SessionUser;goals:Goal[];habits:Habit[];refresh:()=>Promise<void>}){
const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[startDate,setStartDate]=useState(today());const[targetDate,setTargetDate]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[milestones,setMilestones]=useState<Record<string,import('./lib/types').Milestone[]>>({});const[newMilestone,setNewMilestone]=useState<Record<string,string>>({});
useEffect(()=>{Promise.all(goals.map(async g=>[g.id,await api.getMilestones(g.id,user.id)] as const)).then(x=>setMilestones(Object.fromEntries(x))).catch(e=>setError((e as Error).message))},[goals,user.id]);
async function add(){if(!title.trim())return;setBusy(true);setError('');try{await api.saveGoal({user_id:user.id,title:title.trim(),description:description.trim()||null,start_date:startDate||null,target_date:targetDate||null,status:'active'});setTitle('');setDescription('');setTargetDate('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function toggleGoal(g:Goal){setBusy(true);try{await api.setGoalStatus(g.id,user.id,g.status==='completed'?'active':'completed');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function removeGoal(g:Goal){if(!window.confirm(`حذف الهدف «${g.title}»؟\nسيتم حذف المراحل المرتبطة به أيضًا.`))return;setBusy(true);try{await api.deleteGoal(g.id,user.id);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function addMilestone(g:Goal){const t=(newMilestone[g.id]||'').trim();if(!t)return;try{const m=await api.saveMilestone({user_id:user.id,goal_id:g.id,title:t,position:(milestones[g.id]?.length||0)});setMilestones(x=>({...x,[g.id]:[...(x[g.id]||[]),m]}));setNewMilestone(x=>({...x,[g.id]:''}))}catch(e){setError((e as Error).message)}}
async function toggleMilestone(m:import('./lib/types').Milestone,g:Goal){try{const x=await api.toggleMilestone(m.id,user.id,!m.completed);setMilestones(v=>({...v,[g.id]:(v[g.id]||[]).map(i=>i.id===x.id?x:i)}))}catch(e){setError((e as Error).message)}}
async function removeMilestone(m:import('./lib/types').Milestone,g:Goal){try{await api.deleteMilestone(m.id,user.id);setMilestones(v=>({...v,[g.id]:(v[g.id]||[]).filter(i=>i.id!==m.id)}))}catch(e){setError((e as Error).message)}}
return <Page title="أهدافي" sub="الصورة الكبيرة، متقسمة لخطوات صغيرة."><div className="card"><div className="goal-create"><input placeholder="اسم الهدف…" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="ليه الهدف ده مهم ليك؟ (اختياري)" value={description} onChange={e=>setDescription(e.target.value)}/><div className="form-grid"><label>البداية<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>النهاية<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/></label></div><button className="primary" onClick={add} disabled={busy||!title.trim()}><Plus size={18}/> إضافة الهدف</button></div>{error&&<div className="error goal-error">{error}</div>}</div>
<div className="grid two">{goals.map(g=>{const ms=milestones[g.id]||[];const progress=ms.length?Math.round(ms.filter(m=>m.completed).length/ms.length*100):(g.status==='completed'?100:0);return <div className={`card goal-card ${g.status==='completed'?'goal-completed':''}`} key={g.id}><div className="goal-top"><div className="goal-icon"><Target size={20}/></div><span className={`badge ${g.status==='completed'?'success':''}`}>{g.status==='active'?'نشط':g.status==='completed'?'مكتمل':'متوقف'}</span></div><h2>{g.title}</h2><p>{g.description||'هدف جديد في رحلتك.'}</p><div className="goal-meta">{g.start_date&&<span>بدأ: {g.start_date}</span>}{g.target_date&&<span>النهاية: {g.target_date}</span>}</div><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="goal-progress"><strong>{progress}%</strong><span>{ms.filter(m=>m.completed).length}/{ms.length} مراحل مكتملة</span></div><div className="milestones"><strong>المراحل</strong>{ms.map(m=><div className="milestone" key={m.id}><button className={`check ${m.completed?'done':''}`} onClick={()=>toggleMilestone(m,g)}>{m.completed&&<Check size={13}/>}</button><span className={m.completed?'strike':''}>{m.title}</span><button className="trash" onClick={()=>removeMilestone(m,g)}><Trash2 size={14}/></button></div>)}<div className="milestone-add"><input placeholder="أضف مرحلة…" value={newMilestone[g.id]||''} onChange={e=>setNewMilestone(x=>({...x,[g.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addMilestone(g)}}}/><button className="secondary" onClick={()=>addMilestone(g)}><Plus size={15}/></button></div></div><div className="goal-actions"><button className="secondary" onClick={()=>toggleGoal(g)} disabled={busy}><Check size={16}/>{g.status==='completed'?'إعادة فتح الهدف':'تم إتمام الهدف'}</button><button className="danger" onClick={()=>removeGoal(g)} disabled={busy}><Trash2 size={16}/> حذف</button></div></div>})}{!goals.length&&<Empty text="لسه مفيش أهداف. اكتب أول حاجة عايز تغيّرها في نفسك."/>}</div>
<h2 className="page-sub">عاداتي 🌱</h2><HabitManager user={user} goals={goals} habits={habits} refresh={refresh}/></Page>}
function HabitManager({user,goals,habits,refresh}:{user:SessionUser;goals:Goal[];habits:Habit[];refresh:()=>Promise<void>}){const[title,setTitle]=useState('');const[frequency,setFrequency]=useState('يومي');const[target,setTarget]=useState('7');const[goalId,setGoalId]=useState('');const[busy,setBusy]=useState(false);const[logs,setLogs]=useState<import('./lib/types').HabitLog[]>([]);const from=addDaysKey(today(),-30);useEffect(()=>{api.getHabitLogs(user.id,from,today()).then(setLogs).catch(()=>{})},[user.id,habits.length]);const todayDone=(id:string)=>logs.some(l=>l.habit_id===id&&l.log_date===today()&&l.completed);async function add(){if(!title.trim())return;setBusy(true);try{await api.saveHabit({user_id:user.id,title:title.trim(),frequency,target_per_week:Number(target),goal_id:goalId||null,days_of_week:[0,1,2,3,4,5,6],active:true});setTitle('');await refresh();}catch(e){alert((e as Error).message)}finally{setBusy(false)}}async function toggle(h:Habit){try{const l=await api.logHabit(h.id,user.id,today(),!todayDone(h.id));setLogs(x=>[...x.filter(i=>i.id!==l.id),l])}catch(e){alert((e as Error).message)}}async function remove(h:Habit){if(!confirm(`حذف العادة «${h.title}»؟`))return;try{await api.deleteHabit(h.id,user.id);await refresh()}catch(e){alert((e as Error).message)}}return <><div className="card"><div className="habit-create"><input placeholder="اسم العادة…" value={title} onChange={e=>setTitle(e.target.value)}/><div className="form-grid"><select value={frequency} onChange={e=>setFrequency(e.target.value)}><option>يومي</option><option>أسبوعي</option></select><input type="number" min="1" max="7" value={target} onChange={e=>setTarget(e.target.value)}/>{goals.length>0&&<select value={goalId} onChange={e=>setGoalId(e.target.value)}><option value="">بدون هدف</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select>}</div><button className="primary" onClick={add} disabled={busy||!title.trim()}><Plus size={18}/> إضافة عادة</button></div></div><div className="card">{habits.length?habits.map(h=><div className="habit" key={h.id}><button className={`check ${todayDone(h.id)?'done':''}`} onClick={()=>toggle(h)}>{todayDone(h.id)&&<Check size={14}/>}</button><div className="habit-main"><strong className={todayDone(h.id)?'strike':''}>{h.title}</strong><span>{h.frequency} • الهدف {h.target_per_week}/أسبوع</span></div><span className="dot">{todayDone(h.id)?'تم اليوم ✓':'اليوم لم تتم'}</span><button className="trash" onClick={()=>remove(h)}><Trash2 size={16}/></button></div>):<Empty text="أضف أول عادة وخليها خطوة قابلة للقياس."/>}</div></>}
function History({user,tasks,habits}:{user:SessionUser;tasks:Task[];habits:Habit[]}){const[selected,setSelected]=useState(today());const[logs,setLogs]=useState<import('./lib/types').HabitLog[]>([]);const startMonth=monthStartKey(selected);const endMonth=monthEndKey(selected);useEffect(()=>{api.getHabitLogs(user.id,startMonth,endMonth).then(setLogs).catch(()=>{})},[user.id,startMonth,endMonth]);const dayTasks=tasks.filter(t=>t.task_date===selected);const dayLogs=logs.filter(l=>l.log_date===selected&&l.completed);const total=dayTasks.length+habits.filter(h=>h.active).length;const completed=dayTasks.filter(t=>t.status==='completed').length+dayLogs.length;const days=[...new Set(tasks.map(t=>t.task_date).concat(logs.map(l=>l.log_date)))].sort().reverse();return <Page title="السجل" sub="اختار يوم وشوف اللي حصل فعلًا."><div className="card calendar-card"><label>اليوم<input type="date" value={selected} onChange={e=>setSelected(e.target.value)}/></label><div className="history-summary"><strong>{pct(completed,total)}%</strong><span>إنجاز اليوم</span></div></div><div className="grid two"><div className="card"><div className="section-head"><h2>{fmtDate(selected)}</h2><span>{completed} من {total}</span></div>{dayTasks.map(t=><TaskRow key={t.id} task={t} mine={false}/>)}{habits.filter(h=>h.active).map(h=>{const d=dayLogs.some(l=>l.habit_id===h.id);return <div className="task" key={h.id}><span className={`history-dot ${d?'done':''}`}>{d?'✓':'·'}</span><div className="task-main"><strong>{h.title}</strong><span>عادة • {d?'مكتملة':'لم تكتمل'}</span></div></div>})}{!dayTasks.length&&!habits.length&&<Empty text="مفيش نشاط مسجل في اليوم ده."/>}</div><div className="card"><h2>أيام النشاط</h2><div className="history-list">{days.map(d=>{const ts=tasks.filter(t=>t.task_date===d),hl=logs.filter(l=>l.log_date===d&&l.completed),n=ts.filter(t=>t.status==='completed').length+hl.length,t=ts.length+habits.filter(h=>h.active).length;return <button className={`history-day history-button ${d===selected?'selected':''}`} key={d} onClick={()=>setSelected(d)}><div><strong>{fmtDate(d)}</strong><span>{n} إنجاز</span></div><b>{pct(n,t)}%</b></button>})}{!days.length&&<Empty text="السجل هيبدأ يظهر مع أول يوم تسجل فيه خطواتك."/>}</div></div></div></Page>}
function Partner({partner,tasks,goals,habits,onBack}:{partner:Profile;tasks:Task[];goals:Goal[];habits:Habit[];onBack:()=>void}){const todayTasks=tasks.filter(t=>t.task_date===today());return <Page title={`رحلة ${partner.display_name}`} sub="شوف رحلته وادعمه، من غير ما تتدخل في خطواته."><div className="partner-toolbar"><button type="button" id="partner-back-home-button" className="secondary" onClick={(e)=>{e.preventDefault();e.stopPropagation();onBack()}}>← الرجوع للرئيسية</button></div><div className="profile-hero card"><Avatar profile={partner} xl/><div><h2>{partner.display_name}</h2><p>{partner.bio||'لسه بيكتب حكايته.'}</p><span className="profile-gender">{partner.gender==='female'?'أنثى':'ذكر'} • رحلة خاصة</span></div></div><div className="grid two"><div className="card"><div className="section-head"><h2>أهدافه 🎯</h2><span>{goals.filter(g=>g.status==='active').length} نشطة</span></div>{goals.filter(g=>g.status!=='paused').slice(0,5).map(g=><div className="task" key={g.id}><div className="goal-icon"><Target size={17}/></div><div className="task-main"><strong>{g.title}</strong><span>{g.status==='completed'?'مكتمل':'مستمر'}</span></div></div>)}{!goals.length&&<Empty text="لسه مفيش أهداف ظاهرة."/>}</div><div className="card"><div className="section-head"><h2>عاداته 🌱</h2><span>{habits.filter(h=>h.active).length} نشطة</span></div>{habits.filter(h=>h.active).slice(0,6).map(h=><div className="task" key={h.id}><div className="goal-icon">🌱</div><div className="task-main"><strong>{h.title}</strong><span>{h.frequency} • {h.target_per_week} مرات/أسبوع</span></div></div>)}{!habits.length&&<Empty text="لسه مفيش عادات ظاهرة."/>}</div></div><div className="card"><div className="section-head"><h2>خطوات اليوم</h2><span>{todayTasks.filter(t=>t.status==='completed').length}/{todayTasks.length}</span></div>{todayTasks.map(t=><TaskRow key={t.id} task={t} mine={false}/>)}{!todayTasks.length&&<Empty text="مفيش خطوات مسجلة لليوم."/>}</div></Page>}

function Avatar({profile,xl=false,editable=false,onUpload}:{profile:Profile;xl?:boolean;editable?:boolean;onUpload?:(file:File)=>Promise<void>}){
const[busy,setBusy]=useState(false);
const ref=React.useRef<HTMLInputElement>(null);
async function pick(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!onUpload)return;setBusy(true);try{await onUpload(file)}catch(err){alert((err as Error).message)}finally{setBusy(false);e.target.value=''}}
return <div className={`avatar${xl?' xl':''} avatar-wrap${editable?' editable':''}`} onClick={()=>editable&&!busy&&ref.current?.click()} role={editable?'button':undefined} tabIndex={editable?0:undefined} onKeyDown={e=>{if(editable&&(e.key==='Enter'||e.key===' ')){e.preventDefault();ref.current?.click()}}}>{profile.avatar_url?<img src={profile.avatar_url} alt={profile.display_name}/>:(profile.display_name?.[0]||'ر')}{editable&&<span className="avatar-camera"><Camera size={16}/></span>}{editable&&<input ref={ref} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={pick}/>} {busy&&<span className="avatar-loading">…</span>}</div>
}

function ProfileView({profile,onSaved}:{profile:Profile;onSaved:(p:Profile)=>void}){
const[name,setName]=useState(profile.display_name);
const[bio,setBio]=useState(profile.bio||'');
const[gender,setGender]=useState<'male'|'female'>(profile.gender||'male');
const[busy,setBusy]=useState(false);
const[error,setError]=useState('');
useEffect(()=>{setName(profile.display_name);setBio(profile.bio||'');setGender(profile.gender||'male')},[profile.id,profile.display_name,profile.bio,profile.gender]);
async function save(e:React.FormEvent){
  e.preventDefault();
  if(!name.trim())return;
  setBusy(true);setError('');
  try{const updated=await api.updateProfile(profile.id,{display_name:name.trim(),bio:bio.trim()||null,gender});onSaved(updated)}
  catch(e){setError((e as Error).message)}finally{setBusy(false)}
}
return <Page title="ملفي" sub="بياناتك، صورتك، والطريقة اللي تحب رحلتك تظهر بيها."><div className="card profile-edit"><div className="profile-hero"><Avatar profile={{...profile,display_name:name.trim()||profile.display_name}} xl editable onUpload={async(file)=>{const updated=await api.uploadAvatar(profile.id,file);onSaved(updated)}} /><div><h2>{name.trim()||profile.display_name}</h2><p>الصورة والبيانات دي بتظهر للشخص المرتبط بيك.</p></div></div><form onSubmit={save} className="profile-form"><label>الاسم<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} /></label><label>الجنس<select value={gender} onChange={e=>setGender(e.target.value as 'male'|'female')}><option value="male">ذكر</option><option value="female">أنثى</option></select></label><label>نبذة عنك<textarea maxLength={500} placeholder="اكتب نبذة قصيرة عن رحلتك…" value={bio} onChange={e=>setBio(e.target.value)} /></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'جاري الحفظ…':'حفظ التعديلات'}</button></form></div></Page>}
function Page({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="page"><div className="page-head"><h1>{title}</h1><p>{sub}</p></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty"><div>✦</div><p>{text}</p></div>}
function Stat({label,value,icon}:{label:string;value:string;icon:string}){return <div className="card stat"><span>{icon}</span><div><strong>{value}</strong><small>{label}</small></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
